### ISSUE TITLE
LSP attaches to all buffers.

### ISSUE THREAD

**Issue by dsully** [zbirenbaum/copilot.lua#16]
Currently the LSP client appears to attach to all buffers, including ones like `Packer`, `nofile`, etc.

It would be nice to have it take a table of ignored file and buffer types.

**Comment by zbirenbaum** [comment]
> Currently the LSP client appears to attach to all buffers, including ones like `Packer`, `nofile`, etc.
> 
> It would be nice to have it take a table of ignored file and buffer types.

I realized this the other day and was thinking about how to best go about it. I would rather not use a hard coded blacklist, but if I can't find some bufvar they have in common, I will. 

I may move this functionality to the user config, so that they can write exceptions for whatever plugins the use, and put packer, nofile, etc as defaults.

**Comment by zbirenbaum** [comment]
Ok so I took a bit to look into this and there are a few things:

First, copilot is in an interesting position as it has no dedicated filetype. I was thinking about making a whitelist since that's what other lsp do, but I think a blacklist makes much more sense.

That said, there's some strange behavior with filetype detection for some filetype i experimented with as an upstream issue. 

I managed to fix it and get a functional blacklist going, but to make sure it doesn't break with 0.6 I had to do some messy stuff. Since 0.7 releases in 3 days I really, really don't want to add more junk to work around 0.6's limitations.

I'll consider adding this for 0.7 immediately if the way I implement it for just 0.7 doesn't affect current 0.6 behavior, but not if it breaks current 0.6 behavior.

**Comment by dsully** [comment]
Got it. I'm using nightly anyways.

I think this is similar, as fidget.nvim which has an ignore list: https://github.com/j-hui/fidget.nvim/blob/main/lua/fidget.lua#L334

**Comment by zbirenbaum** [comment]
The primary issue is that plugins have a tendency to set its their own filetypes. For example, :LspInfo window is lspconfig, packer window is packer, with a blacklist, people will be stuck adding to it constantly. With a whitelist, the number of programming languages people feasibly use is set. Even if it's not, the number that copilot has been trained on certainly is. 

It's a bit difficult to decide tbh. I'll push an update in a minute with a blacklist, but I may swap it to a whitelist at some point, just a heads up.

**Comment by zbirenbaum** [comment]
So all those non 'real' buffers like packer, terminal, lspinfo, etc, have two traits:
1. They aren't listed
2. They generally have a special buftype like 'help' 'nowrite' etc

I wrote in a check independent of ft_disable in the parameters, so you should be fine, but if, for instance, you want to disable copilot for C or something, you can do so through ft_disable.

For now I like this method so unless something comes up it should stay this way.
