### ISSUE TITLE
Idea: Depend on upstream copilot plugin

### ISSUE THREAD

**Issue by johnf** [zbirenbaum/copilot.lua#26]
@zbirenbaum I noticed you recently updated the copilot code.
Have you thought about removing it from this repo and having only the wrapper and then having folks install the github pluginas well.
You could then load it directly and not have to keep updating it here.

I played with this a little when I was doing some testing and you can set some global variables that tells copilot.vim to not load itself. Mainly by telling it not to manage any file extension types.

**Comment by zbirenbaum** [comment]
I have considered it, but the goal here is ultimately to replace all copilot.vim functionality, and it seems bloated to have a whole plugin as a requirement for just a couple files.

I'll just make a cron job or CI/CD after I finish the update I'm working on that pulls down copilot.vim updates whenever their copilot dist changes

**Comment by zbirenbaum** [comment]
So I'm gonna close this because Microsoft keeps doing stuff to break copilot when they update and I don't want to have to keep rolling it back manually. The last couple updates are a perfect example of this, and I still can't figure out why copilot.vim works with the new agent.js but copilot.lua generates legitimate gigabytes of error messages within minutes. 

That's really not the type of issue I want going live, so depending on copilot.vim directly likely isn't the best solution
