### ISSUE TITLE
Error while processing TextChangedI Autocommands

### ISSUE THREAD

**Issue by kyle-mccarthy** [zbirenbaum/copilot.lua#4]
Hey, this looks awesome! I am trying to get it set up but am having issues with some filetypes. For instance, I get this when editing a json file:

```
Error detected while processing TextChangedI Autocommands for "*":
method getCompletions is not supported by any of the servers registered for the current buffer
```

- platform: macos 12.2.1
- neovim: v0.6.1
- copilot.lua: latest
- copilot-cmp: latest

**Comment by kyle-mccarthy** [comment]
this may have actually been fixed when I removed the github copilot plugin. I'll reopen this if the issue pops back up!

**Comment by zbirenbaum** [comment]
I think this is because the requests are being sent out by the cmp plugin before copilot attaches, but I don't know why you are getting an error, because that doesn't happen to me.

Could you go into :LspInfo and check if copilot is attached to the buffer after reproducing this? It should show up there if it is.

**Comment by kyle-mccarthy** [comment]
Hey, so I went through and removed it from `~/local/share/nvim/site/pack/packer/opt` + then ran PackerSync again and it seems to have fixed it. I can see the results and it gets correctly tagged by cmp. Thank you for the help, I really appreciate it!
