### ISSUE TITLE
Copilot is not completing the whole suggestion

### ISSUE THREAD

**Issue by augustocdias** [zbirenbaum/copilot.lua#42]
I don't know if it is an issue with copilot.lua itself, but perhaps you'll be able to point me out to the right direction.

Lets say I have a code like this and the cursor is at the `|`:

```lua
require('copilot').setup({
    cmp = {
        enabled = true,
        method = "getCompletionsCycling",
    },
    ft_disable = {},
    plugin_manager_path = vim.fn.stdpath("data") .. "/site/pack/packer",
    server_opts_overrides = {},
    |
}
```

If I type `panel` and copilot suggests: 
```lua 
    panel = {
        enabled = true,
    }
```
The result looks like this:

```lua
require('copilot').setup({
    cmp = {
        enabled = true,
        method = "getCompletionsCycling",
    },
    ft_disable = {},
    plugin_manager_path = vim.fn.stdpath("data") .. "/site/pack/packer",
    server_opts_overrides = {},
    panel = {
        enabled = true,

}
```

It won't put the last bracket because it thinks it is already there. If I do the same thing but the cursor between the options where the next character is not the same as the last from the suggestion it works fine.

**Comment by zbirenbaum** [comment]
This is my bad. The idea is that if there's already a closing parenthesis or an 'end' for a function or something it will not insert it. Unfortunately it seems to have some side effects. I need to find a better way of detecting/replacing existing because while the current code functions in most scenarios but ones like this give it trouble and it's too bloated to be maintainable.

It's pretty late at the moment, but I'll look into a better way tomorrow and if I can't find one I'll just remove the current checks until I come up with a better solution.

**Comment by augustocdias** [comment]
I don't know... From the short time I have been using copilot it has been quite aware of where it is in the block to either provide a whole block or none at all.
