### ISSUE TITLE
Error with Copilot starting

### ISSUE THREAD

**Issue by DM1NIK** [zbirenbaum/copilot.lua#82]
There seems to be an issue with the plugin after doing a `:PackerSync` aka updating the plugin.

`:Copilot` :

```bash
Error executing Lua callback: ...nvim/site/pack/packer/opt/copilot.lua/plugin/copilot.lua:15: attempt to concatenate local 'mod_name' (a nil value)                                                        
stack traceback:                                                                                                                                                                                           
        ...nvim/site/pack/packer/opt/copilot.lua/plugin/copilot.lua:15: in function <...nvim/site/pack/packer/opt/copilot.lua/plugin/copilot.lua:8> 
```

Reverting the update completely fixes the problem, but I am unsure why it even happens in the first place. Even though the error still shows up when executing `:Copilot` loads properly into cmp.

The only plugins active to test this are copilot.lua and copilot.cmp

```lua
  use {
    "zbirenbaum/copilot.lua",
    event = "InsertEnter",
    config = function ()
      vim.schedule(function()
        require("copilot").setup()
      end)
    end,
  }
  use {
    "zbirenbaum/copilot-cmp",
    after = { "copilot.lua" },
    config = function ()
      require("copilot_cmp").setup()
    end
  }
```

**Comment by DM1NIK** [comment]
The first time I enter insert mode this error also shows up, but not sure why.

```bash
Spawning language server with cmd: `node` failed. The language server is either not installed, missing
 from PATH, or not executable. 
```

**Comment by zbirenbaum** [comment]
I'm willing to bet this is some edge case with the new methodology for automatic resolution of the copilot agent.js location, but it is strange that you are the only one having it if so.

Could you provide these details:
1. the output of `:lua print(vim.api.nvim_get_runtime_file('copilot/index.js', false)[1])`
2. The output of trying to run `node` on the file provided by the previous command in a terminal

If the above seems to work fine please also provide:
1. OS version and path to neovim plugins dir
2. Output of `node -v` (probably not the issue here but just want to make sure node is installed properly)

**Comment by fecet** [comment]
same issue

**Comment by MunifTanjim** [comment]
#82 reports two issues:
- Error when running `:Copilot`
- Failing to start up

Which one are you facing? @fecet

**Comment by fecet** [comment]
> #82 reports two issues:
> 
> * Error when running `:Copilot`
> * Failing to start up
> 
> Which one are you facing? @fecet

Error when running :Copilot, I have checked https://github.com/zbirenbaum/copilot.lua/pull/83 and solved from this

**Comment by MunifTanjim** [comment]
Nice. Guess we can close this issue.
