### ISSUE TITLE
Word by word suggestions

### ISSUE THREAD

**Issue by mattiasbonte** [zbirenbaum/copilot.lua#85]
Hi,

I was wondering if this would be a suitable thing to implement into this plugin as well?

https://www.reddit.com/r/neovim/comments/z4stsy/how_to_accept_half_or_word_by_word_suggestion_by/
https://github.com/community/community/discussions/12426#discussioncomment-3102062

Cheers.

**Comment by zbirenbaum** [comment]
The code in that post appears to just be splitting the line to show a single word. 

This doesn't exist in Copilot.vim by default and to be honest, I'm not sure what the use case for this would be. The primary purpose of Copilot is to provide full Blocks of code. Anything else, such as variable names, keywords, etc, should be provided by your LSP once they exist. Using Copilot to decide declaration paradigms would likely result in spending more time being spent trying to modify what it comes up with or deciding if it's suggestion is good or not.

I can probably provide a snippet here that will let you do what you want if you place it somewhere in your config, but unless I am understanding the intent here wrong, I'd rather not include it as a config option since it encourages bad practices.

**Comment by olimorris** [comment]
This would be a great addition.

**Comment by MunifTanjim** [comment]
Got a bit of time to take a stab at it: https://github.com/zbirenbaum/copilot.lua/pull/87

Right now, it's just a draft... it doesn't always work with that PR. Need some improvements and some edge case handling.

**Comment by olimorris** [comment]
For everyone's reference, I've just given @MunifTanjim's PR a go and it works brilliantly
